# This is a basic workflow to help you get started with Actions 0389905577

name: vietsub_build

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@v2
            
       - uses: actions/upload-artifact@v3
         with:
          name: vietsub-files
          path: /home/runner/work/overlay/overlay/
